trigger:
  - master

pr:
  - master

resources:
  - repo: self

variables:
  project: '**/api.csproj'
  configuration: 'release'
  pool: Default

stages:
 - stage: Build
   pool: $(pool)
   jobs:
     - job: Build       
       steps:
        - task: DotNetCoreCLI@2
          displayName: restore
          inputs:
            command: 'restore'
            projects: '**/*.csproj'

        - task: DotNetCoreCLI@2
          displayName: build
          inputs:
            command: 'build'
            projects: ${project}
            arguments: '--no-restore -c ${configuration}'

        - task: DotNetCoreCLI@2
          displayName: publish
          inputs:
            command: 'publish'
            projects: ${project}
            zipAfterPublish: true
            publishWebProjects: false
            arguments: '--no-build -c ${configuration} -o $(Build.ArtifactStagingDirectory)'
            
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'