trigger:
  - master

pr:
  - master

variables:
  api-project: "src/Api/Api.csproj"
  fe-project: "src/TestFrontEnd/TestFrontEnd.csproj"
  test-project: "tst/UnitTests/UnitTests.csproj"
  e2e-project: "tst/IntegrationTests/IntegrationTests.csproj"
  configuration: "release"
  pool: Default
  azureSubscriptionId: "f395fc6c-f196-4abe-a248-e9b7d37c9f66"
  azureServiceConnection: "azure-sc"

stages:
  - stage: Api
    dependsOn: []
    jobs:
      - job: Build
        pool: $(pool)
        steps:
          - task: DotNetCoreCLI@2
            displayName: restore
            inputs:
              command: "restore"
              projects: "**/*.csproj"

          - task: DotNetCoreCLI@2
            displayName: build
            inputs:
              command: "build"
              projects: "**/*.csproj"
              arguments: "--no-restore -c $(configuration)"

          - task: DotNetCoreCLI@2
            displayName: "dotnet test"
            inputs:
              publishTestResults: true
              command: "test"
              projects: $(test-project)
              arguments: "--configuration $(configuration) --no-build"
              testRunTitle: "C# Unit Tests"

          - task: DotNetCoreCLI@2
            displayName: publish
            inputs:
              command: "publish"
              projects: $(api-project)
              zipAfterPublish: true
              publishWebProjects: false
              arguments: "--no-build -c $(configuration) -o $(Build.ArtifactStagingDirectory)"

          - task: PublishBuildArtifacts@1
            displayName: "publish artifact api"
            inputs:
              PathtoPublish: "$(Build.ArtifactStagingDirectory)"
              ArtifactName: "api"
              publishLocation: "Container"

  - stage: FrontEnd
    dependsOn: []
    jobs:
      - job: Build
        pool: $(pool)
        steps:
          - task: DotNetCoreCLI@2
            displayName: restore
            inputs:
              command: "restore"
              projects: $(fe-project)

          - task: DotNetCoreCLI@2
            displayName: build
            inputs:
              command: "build"
              projects: $(fe-project)
              arguments: "--no-restore -c $(configuration)"

          - task: DotNetCoreCLI@2
            displayName: publish
            inputs:
              command: "publish"
              projects: $(fe-project)
              zipAfterPublish: true
              publishWebProjects: false
              arguments: "--no-build -c $(configuration) -o $(Build.ArtifactStagingDirectory)"

          - task: PublishBuildArtifacts@1
            displayName: "publish artifact frontend"
            inputs:
              PathtoPublish: "$(Build.ArtifactStagingDirectory)"
              ArtifactName: "frontend"
              publishLocation: "Container"

  - stage: Deploy
    dependsOn:
      - Api
      - FrontEnd
    jobs:
      - deployment: Deploy
        pool: $(pool)
        environment: brandaris
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureCLI@2
                  displayName: Biceps deployment via CLI
                  inputs:
                    azureSubscription: $(azureServiceConnection)
                    scriptType: "pscore"
                    scriptLocation: "inlineScript"
                    inlineScript: "az deployment group create -f $(Build.SourcesDirectory)/deploy/bicep/main.bicep -g brandaris -p $(Build.SourcesDirectory)/deploy/bicep/parameters.ci.json sql_administratorLoginPassword=$(sql_administratorLoginPassword) fe_clientsecret=$(fe_clientsecret)"

                - task: AzureRmWebAppDeployment@4
                  displayName: Deploy API
                  inputs:
                    ConnectionType: "AzureRM"
                    azureSubscription: $(azureServiceConnection)
                    appType: "apiApp"
                    WebAppName: "brandaris-api"
                    packageForLinux: "$(Pipeline.Workspace)/api/Api.zip"

                - task: AzureRmWebAppDeployment@4
                  displayName: Deploy FrontEnd
                  inputs:
                    ConnectionType: "AzureRM"
                    azureSubscription: $(azureServiceConnection)
                    appType: "webApp"
                    WebAppName: "brandaris-frontend"
                    packageForLinux: "$(Pipeline.Workspace)/frontend/TestFrontEnd.zip"

  - stage: E2ETest
    dependsOn:
      - Deploy
    jobs:
      - job: E2ETest
        pool: $(pool)
        steps:
          - task: DotNetCoreCLI@2
            displayName: restore
            inputs:
              command: "restore"
              projects: "**/*.csproj"

          - task: DotNetCoreCLI@2
            displayName: build
            inputs:
              command: "build"
              projects: "**/*.csproj"
              arguments: "--no-restore -c $(configuration)"

          - task: DotNetCoreCLI@2
            displayName: "dotnet test"
            inputs:
              publishTestResults: true
              command: "test"
              projects: $(e2e-project)
              arguments: "--configuration $(configuration) --no-build"
              testRunTitle: "C# E2E Tests"
