trigger:
  - master

pr:
  - master

variables:
  project: 'src/api/api.csproj'
  configuration: 'release'
  pool: Default
  azureSubscriptionId: 'f395fc6c-f196-4abe-a248-e9b7d37c9f66'
  azureServiceConnection: 'azure-sc'

stages:
 - stage: Build
   jobs:
     - job: Build
       pool: $(pool)
       steps:
        - task: DotNetCoreCLI@2
          displayName: restore
          inputs:
            command: 'restore'
            projects: $(project)
        - task: DotNetCoreCLI@2
          displayName: build
          inputs:
            command: 'build'
            projects: $(project)
            arguments: '--no-restore -c $(configuration)'
        - task: DotNetCoreCLI@2
          displayName: publish
          inputs:
            command: 'publish'
            projects: $(project)
            zipAfterPublish: true
            publishWebProjects: false
            arguments: '--no-build -c $(configuration) -o $(Build.ArtifactStagingDirectory)'
        - task: PublishBuildArtifacts@1
          displayName: "publish artifact api"
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'api'
            publishLocation: 'Container'
            


 - stage: ARM
   dependsOn: Build
   jobs:
   - deployment: Deploy
     pool: $(pool)
     environment: brandaris-arm
     strategy:
      runOnce:
        deploy:
          steps:
           - task: AzureResourceManagerTemplateDeployment@3
             displayName: ARM deployment for ARM
             inputs:
               deploymentScope: 'Resource Group'
               azureResourceManagerConnection: $(azureServiceConnection)
               subscriptionId: $(azureSubscriptionId)
               action: 'Create Or Update Resource Group'
               resourceGroupName: 'brandaris-arm'
               location: 'West Europe'
               templateLocation: 'Linked artifact'
               csmFile: 'deploy/arm_template/azuredeploy.json'
               csmParametersFile: 'deploy/arm_template/azuredeploy.parameters.ci.json'
               deploymentMode: 'Incremental'

           - task: AzureRmWebAppDeployment@4
             displayName: Deploy API
             inputs:
               ConnectionType: 'AzureRM'
               azureSubscription: $(azureServiceConnection)
               appType: 'apiApp'
               WebAppName: 'brandaris-api-arm'
               packageForLinux: '$(Pipeline.Workspace)/api/api.zip'

 - stage: Biceps
   dependsOn: Build
   jobs:
   - deployment: Deploy
     pool: $(pool)
     environment: brandaris-biceps
     strategy:
      runOnce:
        deploy:
          steps:
          
           - task: AzureCLI@2
             inputs:
               azureSubscription: 'azure-sc'
               scriptType: 'bash'
               scriptLocation: 'scriptPath'
               scriptPath: '$(Build.SourcesDirectory)/deploy/bicep/deploy-ci.sh'
        
           - task: AzureRmWebAppDeployment@4
             displayName: Deploy API
             inputs:
               ConnectionType: 'AzureRM'
               azureSubscription: $(azureServiceConnection)
               appType: 'apiApp'
               WebAppName: 'brandaris-api-biceps'
               packageForLinux: '$(Pipeline.Workspace)/api/api.zip'
