trigger:
  - master

pr:
  - master

variables:
  project: 'src/api/api.csproj'
  configuration: 'release'
  pool: Default

stages:
 - stage: Build
   jobs:
     - job: Build       
       pool: $(pool)
       steps:
        - task: DotNetCoreCLI@2
          displayName: restore
          inputs:
            command: 'restore'
            projects: $(project)

        - task: DotNetCoreCLI@2
          displayName: build
          inputs:
            command: 'build'
            projects: $(project)
            arguments: '--no-restore -c $(configuration)'

        - task: DotNetCoreCLI@2
          displayName: publish
          inputs:
            command: 'publish'
            projects: $(project)
            zipAfterPublish: true
            publishWebProjects: false
            arguments: '--no-build -c $(configuration) -o $(Build.ArtifactStagingDirectory)'
            
        - task: PublishBuildArtifacts@1
          displayName: "publish api"
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'api'
            publishLocation: 'Container'

 - stage: CI_ARM
   jobs:
     - job: ARM
       pool: $(pool)
       steps:            
        - task: AzureResourceManagerTemplateDeployment@3
          displayName: ARM deployment for CI
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: 'MSDN Premium DutchWorkz(f395fc6c-f196-4abe-a248-e9b7d37c9f66)'
            subscriptionId: 'f395fc6c-f196-4abe-a248-e9b7d37c9f66'
            action: 'Create Or Update Resource Group'
            resourceGroupName: 'brandaris-ci'
            location: 'West Europe'
            templateLocation: 'Linked artifact'
            csmFile: 'deploy/azuredeploy.json'
            csmParametersFile: 'deploy/azuredeploy.parameters.ci.json'
            deploymentMode: 'Incremental'