trigger:
  - master

pr:
  - master

variables:
  project: 'src/api/api.csproj'
  configuration: 'release'
  pool: Default
  subscriptionId: 'f395fc6c-f196-4abe-a248-e9b7d37c9f66'

stages:
 - stage: Build
   jobs:
     - job: Build       
       pool: $(pool)
       steps:
        - task: DotNetCoreCLI@2
          displayName: restore
          inputs:
            command: 'restore'
            projects: $(project)
        - task: DotNetCoreCLI@2
          displayName: build
          inputs:
            command: 'build'
            projects: $(project)
            arguments: '--no-restore -c $(configuration)'
        - task: DotNetCoreCLI@2
          displayName: publish
          inputs:
            command: 'publish'
            projects: $(project)
            zipAfterPublish: true
            publishWebProjects: false
            arguments: '--no-build -c $(configuration) -o $(Build.ArtifactStagingDirectory)'            
        - task: PublishBuildArtifacts@1
          displayName: "publish api"
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'api'
            publishLocation: 'Container'

 - stage: CI
   dependsOn: Build
   jobs:
   - deployment: Deploy
     pool: $(pool)
     environment: brandaris-ci
     strategy:
      runOnce:
        deploy:
          steps:            
           - task: AzureResourceManagerTemplateDeployment@3
             displayName: ARM deployment for CI
             inputs:
               deploymentScope: 'Resource Group'
               azureResourceManagerConnection: brandaris-ci
               subscriptionId: $(subscriptionId)
               action: 'Create Or Update Resource Group'
               resourceGroupName: 'brandaris-ci'
               location: 'West Europe'
               templateLocation: 'Linked artifact'
               csmFile: 'deploy/azuredeploy.json'
               csmParametersFile: 'deploy/azuredeploy.parameters.ci.json'
               deploymentMode: 'Incremental'
           - task: DownloadPipelineArtifact@2
             displayName: Download artifact
             inputs:
               buildType: 'current'
               artifactName: 'api'
               targetPath: '$(Pipeline.Workspace)'
           - task: AzureRmWebAppDeployment@4
             inputs:
               ConnectionType: 'AzureRM'
               azureSubscription: brandaris-ci
               appType: 'apiApp'
               WebAppName: 'brandaris-api-ci'
               packageForLinux: '$(Pipeline.Workspace)/api.zip'

 - stage: Test
   dependsOn: CI
   jobs:
   - deployment: Deploy
     pool: $(pool)
     environment: brandaris-test
     strategy:
      runOnce:
        deploy:
          steps:            
           - task: AzureResourceManagerTemplateDeployment@3
             displayName: ARM deployment for Test
             inputs:
               deploymentScope: 'Resource Group'
               azureResourceManagerConnection: brandaris-test
               subscriptionId: $(subscriptionId)
               action: 'Create Or Update Resource Group'
               resourceGroupName: 'brandaris-test'
               location: 'West Europe'
               templateLocation: 'Linked artifact'
               csmFile: 'deploy/azuredeploy.json'
               csmParametersFile: 'deploy/azuredeploy.parameters.test.json'
               deploymentMode: 'Incremental'
           - task: DownloadPipelineArtifact@2
             displayName: Download artifact
             inputs:
               buildType: 'current'
               artifactName: 'api'
               targetPath: '$(Pipeline.Workspace)'
           - task: AzureRmWebAppDeployment@4
             inputs:
               ConnectionType: 'AzureRM'
               azureSubscription: brandaris-test
               appType: 'apiApp'
               WebAppName: 'brandaris-api-test'
               packageForLinux: '$(Pipeline.Workspace)/api.zip'