trigger:
  - master

pr:
  - master

resources:
  - repo: self

variables:
  project: './src/api/api.csproj'
  configuration: 'release'
  pool: Default

stages:
 - stage: Build
   jobs:
     - job: Build
       pool: $(pool)
       steps:
        - task: DotNetCoreCLI@2
          displayName: restore
          inputs:
            command: 'restore'
            projects: ${project}
            feedsToUse: 'select'

        - task: DotNetCoreCLI@2
          displayName: build
          inputs:
            command: 'build'
            projects: ${project}
            arguments: '--no-restore -c ${configuration}'

        - task: DotNetCoreCLI@2
          displayName: poublish
          inputs:
            command: 'publish'
            projects: ${project}
            zipAfterPublish: true
            arguments: '--no-build -c ${configuration}'
            
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'